// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzlK7jK5TBhdUaZHy4tZ0zBNMmo7H_Ijs',
    appId: '1:432425335651:web:5fc2fc53481d6255c97156',
    messagingSenderId: '432425335651',
    projectId: 'app7pushnot',
    authDomain: 'app7pushnot.firebaseapp.com',
    storageBucket: 'app7pushnot.appspot.com',
    measurementId: 'G-JXC4EYXLFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoK9ca22U2pW7i3maCaFHJCjFlZ7DqlPc',
    appId: '1:432425335651:android:30edc3b3dd735a16c97156',
    messagingSenderId: '432425335651',
    projectId: 'app7pushnot',
    storageBucket: 'app7pushnot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNLjIsn0dF6r0tzdsVESBek1ZHo6Pa8s',
    appId: '1:432425335651:ios:8dd6bd5071621c0dc97156',
    messagingSenderId: '432425335651',
    projectId: 'app7pushnot',
    storageBucket: 'app7pushnot.appspot.com',
    iosBundleId: 'com.example.app1Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNLjIsn0dF6r0tzdsVESBek1ZHo6Pa8s',
    appId: '1:432425335651:ios:513292ff7ba5df3ec97156',
    messagingSenderId: '432425335651',
    projectId: 'app7pushnot',
    storageBucket: 'app7pushnot.appspot.com',
    iosBundleId: 'com.example.app1Firebase.RunnerTests',
  );
}
